name: build

on: [push, pull_request]

jobs:

  linux:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [
            g++-7, clang++-8
        ]
        mode: [""] # "-DUSE_ASAN=ON", "-DUSE_UBSAN=ON", "-DUSE_THSAN=ON"

    steps:
    - uses: actions/checkout@v2
    - name: Install g++-7
      if: ${{ matrix.compiler == 'g++-7' }}
      run: |
        sudo apt-get update
        sudo apt-get install g++-7 -y
    - name: Install clang-8
      if: ${{ matrix.compiler == 'clang++-8' }}
      run: |
        sudo apt-get update
        sudo apt-get install clang-8 -y
    - name: Create Build folder
      run: mkdir -p build
    - name: Compile tests
      working-directory: build
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        cmake -DFETCH_3RD_PARTY_REPOS=ON ${{ matrix.mode }} ..
        make -j2
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 30 -C Debug -j2

  macos:
    timeout-minutes: 60
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Build folder
      run: mkdir -p build
    - name: Compile tests
      working-directory: build
      run: |
        cmake -DFETCH_3RD_PARTY_REPOS=ON ..
        make -j2
