name: build

on: [push, pull_request]

jobs:
  linux:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [
            g++-9, clang++-8
        ]
        mode: ["", "-DUSE_ASAN:BOOL=TRUE", "-DUSE_UBSAN:BOOL=TRUE", "-DUSE_THSAN:BOOL=TRUE"]

    steps:
    - uses: actions/checkout@v2
    - name: Install compilers and deps
      run: |
        sudo apt-get update \
        && sudo apt-get install clang-8 g++-9 libubsan0 -y \
        && sudo rm -rf /var/lib/apt/lists/*
    - name: Create Build folder
      run: mkdir -p build
    - name: Compile tests
      working-directory: build
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        cmake -DCMAKE_BUILD_TYPE:STRING=MinSizeRel -DFETCH_3RD_PARTY_REPOS:BOOL=TRUE ${{ matrix.mode }} ..
        make -j2
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 30 -C Debug -j2 --output-on-failure

  macos:
    timeout-minutes: 60
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Build folder
      run: mkdir -p build
    - name: Compile tests
      working-directory: build
      run: |
        cmake -DCMAKE_BUILD_TYPE:STRING=MinSizeRel -DFETCH_3RD_PARTY_REPOS=ON ..
        make -j2
