name: Coverage Check
on: [push, pull_request]
jobs:
  coverage:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - name: Install compilers and deps
      run: |
        sudo apt-get update \
        && sudo apt-get install g++-9 libubsan0 gcovr -y \
        && sudo rm -rf /var/lib/apt/lists/*
    - name: Create Build folder
      run: mkdir -p build
    - name: Compile tests
      working-directory: build
      env:
        CXX: g++-9
      run: |
        cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DFETCH_3RD_PARTY_REPOS:BOOL=TRUE -DUSE_TEST_COVERAGE:BOOL=TRUE ..
        make -j2
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: |
        ctest --timeout 30 -T Test -T Coverage -C Debug -j2 --output-on-failure 2>&1 | tee coverage.log
    - name: Extract Coverage Percentage
      working-directory: build
      run: |
        cat coverage.log | grep "Percentage Coverage:" | awk '{print $3}' | sed 's/%//g' > coverage_percentage.txt
        echo -n "$(cat coverage_percentage.txt)" | perl -nl -MPOSIX -e 'print floor($_);' > coverage_percentage_int.txt
        echo -n "orange" > coverage_color.txt
        if (( $(echo "$(cat coverage_percentage_int.txt) >= 80" |bc -l) )); then echo -n "green" > coverage_color.txt; fi
        if (( $(echo "$(cat coverage_percentage_int.txt) < 60" |bc -l) )); then echo -n "red" > coverage_color.txt; fi
        echo "GITHUB_TEST_COVERAGE=$(cat coverage_percentage.txt)" >> $GITHUB_ENV
        echo "GITHUB_TEST_COVERAGE_COLOR=$(cat coverage_color.txt)" >> $GITHUB_ENV
    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 8bbff6da2e3c92e00414d698b4345248
        filename: coverage.json
        label: Coverage
        message: ${{ env.GITHUB_TEST_COVERAGE }} %
        color: ${{ env.GITHUB_TEST_COVERAGE_COLOR }}